export const categoryColors = {
    'Meeting': 'var(--purple-meeting)',
    'Möte': 'var(--purple-meeting)',
    'Administrative': 'var(--pink-admin)',
    'Administrativt': 'var(--pink-admin)',
    'Creative': 'var(--orange-creative)',
    'Kreativt': 'var(--orange-creative)',
    'Technical': 'var(--dark-blue-tech)',
    'Tekniskt': 'var(--dark-blue-tech)',
    'Analytical': 'var(--light-green-analytical)',
    'Analytiskt': 'var(--light-green-analytical)',
    'Communication': 'var(--gold-communication)',
    'Kommunikation': 'var(--gold-communication)',
    'Planning': 'var(--light-blue-planning)',
    'Planering': 'var(--light-blue-planning)',
    'Learning': 'var(--fuschsia-learning)',
    'Lärande': 'var(--fuschsia-learning)',
    'Sales & Marketing': 'var(--red-pink-sales)',
    'Försäljning & marknadsföring': 'var(--red-pink-sales)',
    'Support': 'var(--dark-green-support)',
    'Operations': 'var(--yellow-operations)',
    'Verksamhet / Drift': 'var(--yellow-operations)',
    'Other': 'var(--red-other)',
    'Annat': 'var(--red-other)',
}